# -*- coding: utf-8 -*-
"""dashboard_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-ooKt8bRmLSDYqr3gwZYH-uBpfvjS_H
"""

!pip install plotly -q

!pip install streamlit pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard.py
# """
# Smart Energy Usage Predictor — REDESIGNED Dashboard
# Group B11 | Section 5.8 — Dashboard Development only
# 
# HOW TO RUN IN GOOGLE COLAB
# ===========================
# Cell 1 — Install:
#     !pip install streamlit pyngrok plotly -q
# 
# Cell 2 — Save this file:
#     %%writefile dashboard.py
#     <paste entire file here>
# 
# Cell 3 — Launch:
#     from pyngrok import ngrok
#     import subprocess, threading, time
# 
#     def _run():
#         subprocess.run(["streamlit", "run", "dashboard.py",
#                         "--server.port=8501", "--server.headless=true"])
# 
#     threading.Thread(target=_run, daemon=True).start()
#     time.sleep(4)
#     print("Open:", ngrok.connect(8501))
# """
# 
# import warnings
# warnings.filterwarnings("ignore")
# 
# import numpy as np
# import pandas as pd
# import streamlit as st
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.subplots import make_subplots
# import joblib
# import os
# 
# # ── Page config ────────────────────────────────────────────────────────────────
# st.set_page_config(
#     page_title="Smart Energy Usage Predictor",
#     page_icon="⚡",
#     layout="wide",
#     initial_sidebar_state="collapsed"
# )
# 
# # ── Global Theme & CSS ─────────────────────────────────────────────────────────
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Inter:wght@300;400;500;600&display=swap');
# 
# /* ── Base ── */
# html, body, [class*="css"] {
#     font-family: 'Inter', sans-serif;
# }
# .stApp {
#     background: #050d1a;
#     color: #c8d8f0;
# }
# 
# /* ── Header ── */
# .hero-header {
#     background: linear-gradient(135deg, #070f20 0%, #0a1628 60%, #0d1f3c 100%);
#     border: 1px solid #1a3a5c;
#     border-radius: 16px;
#     padding: 28px 36px;
#     margin-bottom: 28px;
#     position: relative;
#     overflow: hidden;
# }
# .hero-header::before {
#     content: '';
#     position: absolute;
#     top: -60px; right: -60px;
#     width: 280px; height: 280px;
#     background: radial-gradient(circle, rgba(0,212,255,0.12) 0%, transparent 70%);
#     pointer-events: none;
# }
# .hero-title {
#     font-family: 'Rajdhani', sans-serif;
#     font-size: 2.6rem;
#     font-weight: 700;
#     letter-spacing: 2px;
#     background: linear-gradient(90deg, #00d4ff, #7b2fff, #00d4ff);
#     background-size: 200%;
#     -webkit-background-clip: text;
#     -webkit-text-fill-color: transparent;
#     animation: shimmer 4s linear infinite;
#     margin: 0 0 4px 0;
# }
# @keyframes shimmer {
#     0%   { background-position: 0%   }
#     100% { background-position: 200% }
# }
# .hero-sub {
#     font-size: 0.82rem;
#     color: #5a7fa0;
#     letter-spacing: 3px;
#     text-transform: uppercase;
#     margin: 0;
# }
# 
# /* ── Section titles ── */
# .section-title {
#     font-family: 'Rajdhani', sans-serif;
#     font-size: 1.15rem;
#     font-weight: 600;
#     letter-spacing: 2px;
#     text-transform: uppercase;
#     color: #00d4ff;
#     border-left: 3px solid #00d4ff;
#     padding-left: 12px;
#     margin: 30px 0 18px 0;
#     display: flex;
#     align-items: center;
#     gap: 8px;
# }
# 
# /* ── KPI Cards ── */
# .kpi-row {
#     display: grid;
#     grid-template-columns: repeat(4, 1fr);
#     gap: 16px;
#     margin-bottom: 24px;
# }
# .kpi-card {
#     background: linear-gradient(145deg, #0a1628, #0d1f3c);
#     border: 1px solid #1a3a5c;
#     border-radius: 12px;
#     padding: 18px 20px;
#     position: relative;
#     overflow: hidden;
#     transition: border-color 0.3s;
# }
# .kpi-card::after {
#     content: '';
#     position: absolute;
#     bottom: 0; left: 0; right: 0;
#     height: 2px;
#     background: linear-gradient(90deg, #00d4ff, #7b2fff);
# }
# .kpi-label {
#     font-size: 0.68rem;
#     letter-spacing: 2px;
#     text-transform: uppercase;
#     color: #5a7fa0;
#     margin-bottom: 8px;
# }
# .kpi-value {
#     font-family: 'Rajdhani', sans-serif;
#     font-size: 2rem;
#     font-weight: 700;
#     color: #e8f4ff;
#     line-height: 1;
# }
# .kpi-unit {
#     font-size: 0.75rem;
#     color: #5a7fa0;
#     margin-top: 4px;
# }
# .kpi-delta-pos { color: #00e676; font-size: 0.8rem; }
# .kpi-delta-neg { color: #ff5252; font-size: 0.8rem; }
# 
# /* ── Alert pills ── */
# .alert-high {
#     background: rgba(255,50,50,0.08);
#     border: 1px solid rgba(255,50,50,0.4);
#     border-left: 4px solid #ff3232;
#     padding: 10px 16px;
#     border-radius: 0 8px 8px 0;
#     font-size: 0.85rem;
#     margin: 6px 0;
#     color: #ffb3b3;
# }
# .alert-med {
#     background: rgba(255,180,0,0.08);
#     border: 1px solid rgba(255,180,0,0.4);
#     border-left: 4px solid #ffb400;
#     padding: 10px 16px;
#     border-radius: 0 8px 8px 0;
#     font-size: 0.85rem;
#     margin: 6px 0;
#     color: #ffe082;
# }
# .alert-ok {
#     background: rgba(0,230,118,0.08);
#     border: 1px solid rgba(0,230,118,0.4);
#     border-left: 4px solid #00e676;
#     padding: 10px 16px;
#     border-radius: 0 8px 8px 0;
#     font-size: 0.85rem;
#     margin: 6px 0;
#     color: #a5ffcd;
# }
# 
# /* ── Toggle + slider overrides ── */
# div[data-testid="stToggle"] label {
#     color: #8ab4d8 !important;
# }
# .stSlider > div > div { background: #1a3a5c; }
# .stNumberInput input {
#     background: #0a1628 !important;
#     border: 1px solid #1a3a5c !important;
#     color: #c8d8f0 !important;
#     border-radius: 8px !important;
# }
# 
# /* ── Metric override ── */
# div[data-testid="metric-container"] {
#     background: #0a1628;
#     border: 1px solid #1a3a5c;
#     border-radius: 10px;
#     padding: 14px 18px;
# }
# div[data-testid="metric-container"] label {
#     color: #5a7fa0 !important;
#     font-size: 0.72rem !important;
#     letter-spacing: 1.5px !important;
#     text-transform: uppercase;
# }
# div[data-testid="metric-container"] [data-testid="metric-value"] {
#     font-family: 'Rajdhani', sans-serif !important;
#     font-size: 1.6rem !important;
#     color: #e8f4ff !important;
# }
# 
# /* ── Expander ── */
# .streamlit-expanderHeader {
#     background: #0a1628 !important;
#     border: 1px solid #1a3a5c !important;
#     border-radius: 10px !important;
#     color: #8ab4d8 !important;
#     font-size: 0.85rem !important;
#     letter-spacing: 1px;
# }
# 
# /* ── Dataframe ── */
# .stDataFrame { border: 1px solid #1a3a5c; border-radius: 10px; overflow: hidden; }
# 
# /* ── Divider ── */
# hr { border-color: #1a3a5c !important; margin: 28px 0 !important; }
# 
# /* ── Footer ── */
# .footer {
#     text-align: center;
#     padding: 20px;
#     font-size: 0.72rem;
#     letter-spacing: 2px;
#     text-transform: uppercase;
#     color: #2a4a6c;
#     border-top: 1px solid #1a3a5c;
#     margin-top: 40px;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ── Plotly dark theme defaults ─────────────────────────────────────────────────
# PLOTLY_LAYOUT = dict(
#     paper_bgcolor="rgba(0,0,0,0)",
#     plot_bgcolor="rgba(0,0,0,0)",
#     font=dict(family="Inter", color="#8ab4d8", size=11),
#     title_font=dict(family="Rajdhani", color="#c8d8f0", size=14),
#     xaxis=dict(
#         gridcolor="#0f2540", linecolor="#1a3a5c",
#         tickfont=dict(color="#5a7fa0"),
#         title_font=dict(color="#5a7fa0"),
#     ),
#     yaxis=dict(
#         gridcolor="#0f2540", linecolor="#1a3a5c",
#         tickfont=dict(color="#5a7fa0"),
#         title_font=dict(color="#5a7fa0"),
#     ),
#     legend=dict(
#         bgcolor="rgba(5,13,26,0.7)", bordercolor="#1a3a5c",
#         font=dict(color="#8ab4d8"), borderwidth=1,
#     ),
#     margin=dict(l=16, r=16, t=42, b=16),
#     hoverlabel=dict(
#         bgcolor="#0a1628", bordercolor="#1a3a5c",
#         font=dict(color="#e8f4ff"),
#     ),
# )
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # DATA LOADING
# # ══════════════════════════════════════════════════════════════════════════════
# APPLIANCES = ["Television", "Dryer", "Oven", "Refrigerator", "Microwave"]
# 
# @st.cache_data(show_spinner=False)
# def load_data():
#     df = pd.read_csv("final_processed_data.csv")
# 
#     if "Unix Timestamp" in df.columns:
#         ts = pd.to_datetime(df["Unix Timestamp"], unit="s")
#         df["hour"] = ts.dt.hour
#         df["day"]  = ts.dt.dayofyear
#     else:
#         df["hour"] = df.get("hour", 0)
#         df["day"]  = df.get("day",  0)
# 
#     energy_col = "Energy Consumption (kWh)"
#     if energy_col in df.columns:
#         df["energy"] = df[energy_col]
#     elif "energy" not in df.columns:
#         raise ValueError("Cannot find energy column in final_processed_data.csv")
# 
#     if "predicted" not in df.columns:
#         df["predicted"] = df["energy"]
# 
#     mean_op = df.loc[df["hour"].between(0, 4), "energy"].mean()
#     std_op  = df.loc[df["hour"].between(0, 4), "energy"].std()
#     p95     = df["energy"].quantile(0.95)
# 
#     df["offpeak_alert"]   = (df["hour"].between(0, 4)) & (df["energy"] > mean_op + 2 * std_op)
#     df["spike_alert"]     = df["energy"] > p95
#     df["prolonged_alert"] = df[["Dryer", "Oven"]].sum(axis=1) >= 1
# 
#     if "Is_Anomaly" in df.columns:
#         df["wastage_flag"] = (df["offpeak_alert"] | df["spike_alert"] |
#                                df["prolonged_alert"] | df["Is_Anomaly"])
#     else:
#         df["wastage_flag"] = (df["offpeak_alert"] | df["spike_alert"] | df["prolonged_alert"])
# 
#     return df, p95, mean_op + 2 * std_op
# 
# 
# @st.cache_resource(show_spinner=False)
# def load_model():
#     if os.path.exists("energy_model.pkl"):
#         return joblib.load("energy_model.pkl")
#     return None
# 
# 
# df, P95, OFFPEAK_THR = load_data()
# model_pipeline = load_model()
# 
# MODEL_FEATURES = None
# if model_pipeline is not None:
#     try:
#         scaler = model_pipeline.named_steps.get("scaler")
#         if hasattr(scaler, "feature_names_in_"):
#             MODEL_FEATURES = list(scaler.feature_names_in_)
#     except Exception:
#         pass
# 
# 
# def predict_single(tv, dryer, oven, fridge, micro, ap):
#     if model_pipeline is not None and MODEL_FEATURES is not None:
#         try:
#             sample = pd.DataFrame([{f: 0 for f in MODEL_FEATURES}])
#             for col, val in [("Television", tv), ("Dryer", dryer), ("Oven", oven),
#                              ("Refrigerator", fridge), ("Microwave", micro), ("Apparent Power", ap)]:
#                 if col in sample.columns:
#                     sample[col] = val
#             pred = model_pipeline.predict(sample)[0]
#             return round(max(0.0, float(pred)), 4)
#         except Exception:
#             pass
#     val = (ap * 1.5 + dryer * 6.0 + oven * 4.0 + fridge * 1.5 + tv * 0.3 + micro * 0.5)
#     return round(max(0.0, float(val)), 4)
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # HERO HEADER
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown("""
# <div class="hero-header">
#   <p class="hero-title">⚡ SMART ENERGY PREDICTOR</p>
#   <p class="hero-sub">Group B11 · Section 5.8 &nbsp;|&nbsp; Residential Energy Prediction · Wastage Detection · Live Analytics</p>
# </div>
# """, unsafe_allow_html=True)
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # TOP-LEVEL KPI STRIP
# # ══════════════════════════════════════════════════════════════════════════════
# total_energy  = df["energy"].sum()
# avg_hourly    = df["energy"].mean()
# n_total_alert = int(df["wastage_flag"].sum())
# wastage_pct   = round(n_total_alert / len(df) * 100, 1)
# 
# c1, c2, c3, c4 = st.columns(4)
# c1.metric("Total Energy Recorded", f"{total_energy:,.1f} kWh")
# c2.metric("Avg Hourly Consumption", f"{avg_hourly:.3f} kWh")
# c3.metric("Total Wastage Events",  f"{n_total_alert:,}")
# c4.metric("Wastage Incident Rate",  f"{wastage_pct}%")
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # SECTION 1 — Energy Consumption Trends
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown('<div class="section-title">📈 Energy Consumption Trends</div>', unsafe_allow_html=True)
# 
# hourly_avg = df.groupby("hour")["energy"].mean().reset_index()
# daily_avg  = df.groupby("day")["energy"].mean().reset_index()
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     fig = go.Figure()
#     # Off-peak shading
#     fig.add_vrect(x0=-0.5, x1=4.5, fillcolor="rgba(255,50,50,0.07)",
#                   line_width=0, annotation_text="Off-Peak", annotation_position="top left",
#                   annotation_font=dict(color="#ff8080", size=10))
#     fig.add_trace(go.Scatter(
#         x=hourly_avg["hour"], y=hourly_avg["energy"],
#         mode="lines", fill="tozeroy",
#         line=dict(color="#00d4ff", width=2.5),
#         fillcolor="rgba(0,212,255,0.08)",
#         hovertemplate="<b>Hour %{x}:00</b><br>Avg: %{y:.3f} kWh<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     xaxis_config.update(title="Hour", tickvals=list(range(0,24,2)))
#     yaxis_config.update(title="Avg kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Average Energy by Hour of Day",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# with col2:
#     fig = go.Figure()
#     fig.add_trace(go.Scatter(
#         x=daily_avg["day"].values[:120], y=daily_avg["energy"].values[:120],
#         mode="lines", fill="tozeroy",
#         line=dict(color="#7b2fff", width=2),
#         fillcolor="rgba(123,47,255,0.08)",
#         hovertemplate="<b>Day %{x}</b><br>Avg: %{y:.3f} kWh<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     xaxis_config.update(title="Day of Year")
#     yaxis_config.update(title="Avg kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Daily Energy Trend (First 120 Days)",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# st.divider()
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # SECTION 2 — Appliance Inputs + Forecast
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown('<div class="section-title">🔌 Appliance Controls & Forecast</div>', unsafe_allow_html=True)
# 
# with st.expander("⚙️  Configure Appliances & Apparent Power", expanded=True):
#     c1, c2, c3, c4, c5, c6 = st.columns(6)
#     inp_tv    = c1.toggle("Television",    value=True)
#     inp_dryer = c2.toggle("Dryer",         value=False)
#     inp_oven  = c3.toggle("Oven",          value=False)
#     inp_fridge= c4.toggle("Refrigerator",  value=True)
#     inp_micro = c5.toggle("Microwave",     value=False)
#     inp_ap    = c6.number_input("Apparent Power (VA)", min_value=100, max_value=3000, value=500, step=50)
# 
# base_kwh = predict_single(int(inp_tv), int(inp_dryer), int(inp_oven),
#                            int(inp_fridge), int(inp_micro), float(inp_ap))
# 
# rng_fc       = np.random.default_rng(7)
# hour_factors = 0.85 + 0.3 * np.sin(np.linspace(0, 2 * np.pi, 24) - 1.2)
# forecast_24h = np.clip(base_kwh * hour_factors + rng_fc.normal(0, 0.3, 24), 0, None)
# 
# day_factors = 0.9 + 0.2 * np.sin(np.linspace(0, 2 * np.pi, 7))
# forecast_7d = np.clip(base_kwh * 24 * day_factors + rng_fc.normal(0, 2, 7), 0, None)
# day_labels  = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     bar_colors = ["#ff4d4d" if v > P95 else "#00d4ff" for v in forecast_24h]
#     fig = go.Figure()
#     # Threshold line
#     fig.add_hline(y=P95, line=dict(color="#ff4d4d", width=1.5, dash="dash"),
#                   annotation_text=f"95th pct = {P95:.2f}", annotation_position="top right",
#                   annotation_font=dict(color="#ff9999", size=10))
#     fig.add_trace(go.Bar(
#         x=list(range(24)), y=forecast_24h,
#         marker_color=bar_colors,
#         marker_line_width=0,
#         hovertemplate="<b>Hour %{x}:00</b><br>Predicted: %{y:.3f} kWh<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     xaxis_config.update(title="Time", tickvals=list(range(0,24,2)))
#     yaxis_config.update(title="Predicted kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="24-Hour Predicted Consumption",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# with col2:
#     fig = go.Figure()
#     fig.add_trace(go.Bar(
#         x=day_labels, y=forecast_7d,
#         marker=dict(
#             color=forecast_7d,
#             colorscale=[[0, "#0a3a6e"], [0.5, "#0080c8"], [1, "#00d4ff"]],
#             showscale=False,
#             line_width=0,
#         ),
#         text=[f"{v:.1f}" for v in forecast_7d],
#         textposition="outside",
#         textfont=dict(color="#8ab4d8", size=11),
#         hovertemplate="<b>%{x}</b><br>Predicted: %{y:.2f} kWh<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     yaxis_config.update(title="Predicted kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="7-Day Predicted Consumption",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config,
#         showlegend=False
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# m1, m2, m3 = st.columns(3)
# m1.metric("Current Prediction", f"{base_kwh:.3f} kWh")
# m2.metric("24-Hour Total",      f"{forecast_24h.sum():.2f} kWh")
# m3.metric("7-Day Total",        f"{forecast_7d.sum():.2f} kWh")
# 
# st.divider()
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # SECTION 3 — Appliance Energy Contribution
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown('<div class="section-title">🏠 Appliance-Wise Energy Contribution</div>', unsafe_allow_html=True)
# 
# col1, col2 = st.columns(2)
# 
# APPLIANCE_COLORS = ["#00d4ff", "#ff4d4d", "#ffb400", "#00e676", "#b44dff"]
# 
# with col1:
#     on_avg = {a: df.loc[df[a] == 1, "energy"].mean() for a in APPLIANCES}
#     sorted_items = sorted(on_avg.items(), key=lambda x: x[1])
#     names  = [k for k, _ in sorted_items]
#     values = [v for _, v in sorted_items]
# 
#     fig = go.Figure()
#     fig.add_trace(go.Bar(
#         x=values, y=names, orientation="h",
#         marker=dict(
#             color=APPLIANCE_COLORS[:len(names)],
#             line_width=0,
#         ),
#         text=[f"{v:.3f} kWh" for v in values],
#         textposition="outside",
#         textfont=dict(color="#8ab4d8", size=11),
#         hovertemplate="<b>%{y}</b><br>Avg when ON: %{x:.3f} kWh<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     xaxis_config.update(title="Avg kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Average Energy per Appliance (when ON)",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config,
#         showlegend=False
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# with col2:
#     contrib = {
#         "Television":   df["Television"].sum()   * 0.3,
#         "Dryer":        df["Dryer"].sum()         * 6.0,
#         "Oven":         df["Oven"].sum()           * 4.0,
#         "Refrigerator": df["Refrigerator"].sum()  * 1.5,
#         "Microwave":    df["Microwave"].sum()      * 0.5,
#     }
#     fig = go.Figure()
#     fig.add_trace(go.Pie(
#         labels=list(contrib.keys()),
#         values=list(contrib.values()),
#         hole=0.55,
#         marker=dict(colors=APPLIANCE_COLORS, line=dict(color="#050d1a", width=2)),
#         textfont=dict(color="#e8f4ff", size=12),
#         hovertemplate="<b>%{label}</b><br>%{value:.0f} kWh total<br>%{percent}<extra></extra>",
#     ))
#     # Center annotation
#     fig.add_annotation(text="Total<br>Share", x=0.5, y=0.5,
#                        font=dict(size=13, color="#5a7fa0", family="Rajdhani"),
#                        showarrow=False)
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
#     legend_config = layout_copy.pop("legend", {})
# 
#     legend_config.update(orientation="v")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Appliance Share of Total Energy",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config,
#         showlegend=True,
#         legend=legend_config
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# st.divider()
# 
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # SECTION 4 — Wastage Alerts
# # ══════════════════════════════════════════════════════════════════════════════
# st.markdown('<div class="section-title">🚨 Wastage Alert Intelligence</div>', unsafe_allow_html=True)
# 
# n_offpeak   = int(df["offpeak_alert"].sum())
# n_spike     = int(df["spike_alert"].sum())
# n_prolonged = int(df["prolonged_alert"].sum())
# n_total     = int(df["wastage_flag"].sum())
# 
# c1, c2, c3, c4 = st.columns(4)
# c1.metric("Total Alerts",       n_total)
# c2.metric("Off-Peak Anomalies", n_offpeak)
# c3.metric("Consumption Spikes", n_spike)
# c4.metric("Prolonged Usage",    n_prolonged)
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     types  = ["Off-Peak Anomaly", "Consumption Spike", "Prolonged Usage"]
#     counts = [n_offpeak, n_spike, n_prolonged]
#     alert_colors = ["#ffb400", "#ff3232", "#b44dff"]
# 
#     fig = go.Figure()
#     fig.add_trace(go.Bar(
#         x=types, y=counts,
#         marker=dict(color=alert_colors, line_width=0),
#         text=counts,
#         textposition="outside",
#         textfont=dict(color="#8ab4d8", size=13, family="Rajdhani"),
#         hovertemplate="<b>%{x}</b><br>Count: %{y}<extra></extra>",
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     yaxis_config.update(title="Alert Count")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Wastage Alert Breakdown by Type",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config,
#         showlegend=False
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# with col2:
#     norm_avg  = df.loc[~df["wastage_flag"], "energy"].mean()
#     waste_avg = df.loc[ df["wastage_flag"], "energy"].mean()
# 
#     fig = go.Figure()
#     fig.add_trace(go.Bar(
#         x=["Normal Periods", "Wastage Periods"],
#         y=[norm_avg, waste_avg],
#         marker=dict(color=["#00e676", "#ff3232"], line_width=0),
#         text=[f"{norm_avg:.3f}", f"{waste_avg:.3f}"],
#         textposition="outside",
#         textfont=dict(color="#8ab4d8", size=13, family="Rajdhani"),
#         hovertemplate="<b>%{x}</b><br>Avg kWh: %{y:.3f}<extra></extra>",
#         width=0.4,
#     ))
#     layout_copy = PLOTLY_LAYOUT.copy()
#     xaxis_config = layout_copy.pop("xaxis", {})
#     yaxis_config = layout_copy.pop("yaxis", {})
# 
#     yaxis_config.update(title="Avg kWh")
# 
#     fig.update_layout(
#         **layout_copy,
#         title="Average Energy: Normal vs Wastage",
#         xaxis=xaxis_config,
#         yaxis=yaxis_config,
#         showlegend=False
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# # ── Live Alert Panel ───────────────────────────────────────────────────────────
# st.markdown("**⚡ Live Alert Check — Current Input**")
# hour_now = st.slider("Hour of day", 0, 23, 14, key="alert_hr")
# apps_on  = sum([int(inp_tv), int(inp_dryer), int(inp_oven),
#                 int(inp_fridge), int(inp_micro)])
# any_flag = False
# 
# if 0 <= hour_now < 5 and base_kwh > OFFPEAK_THR:
#     st.markdown(
#         f'<div class="alert-high">🔴 <b>HIGH — Off-Peak Anomaly</b> &nbsp;|&nbsp; '
#         f'{hour_now:02d}:00 &nbsp;|&nbsp; '
#         f'{base_kwh:.3f} kWh exceeds threshold ({OFFPEAK_THR:.2f} kWh)</div>',
#         unsafe_allow_html=True)
#     any_flag = True
# 
# if base_kwh > P95:
#     st.markdown(
#         f'<div class="alert-high">🔴 <b>HIGH — Consumption Spike</b> &nbsp;|&nbsp; '
#         f'{hour_now:02d}:00 &nbsp;|&nbsp; '
#         f'{base_kwh:.3f} kWh exceeds 95th pct ({P95:.2f} kWh)</div>',
#         unsafe_allow_html=True)
#     any_flag = True
# 
# if apps_on >= 3:
#     st.markdown(
#         f'<div class="alert-med">🟡 <b>MEDIUM — Prolonged Usage</b> &nbsp;|&nbsp; '
#         f'{hour_now:02d}:00 &nbsp;|&nbsp; '
#         f'{apps_on} appliances ON simultaneously</div>',
#         unsafe_allow_html=True)
#     any_flag = True
# 
# if not any_flag:
#     st.markdown(
#         '<div class="alert-ok">🟢 <b>All Clear</b> — consumption is within normal range.</div>',
#         unsafe_allow_html=True)
# 
# # ── Recent Wastage Records ─────────────────────────────────────────────────────
# st.markdown("**📋 Recent Wastage Records**")
# 
# if os.path.exists("final_causes.csv"):
#     causes_df = pd.read_csv("final_causes.csv")
#     causes_df = causes_df.merge(
#         df[["energy"]].reset_index().rename(columns={"index": "Index"}),
#         on="Index", how="left"
#     )
#     if "Unix Timestamp" in df.columns:
#         causes_df["Timestamp"] = pd.to_datetime(
#             df.loc[causes_df["Index"].values, "Unix Timestamp"].values, unit="s"
#         ).strftime("%Y-%m-%d  %H:%M")
#     else:
#         causes_df["Timestamp"] = pd.to_datetime(
#             1577836800 + causes_df["Index"] * 1800, unit="s"
#         ).dt.strftime("%Y-%m-%d  %H:%M")
#     causes_df["kWh"] = causes_df["energy"].round(3)
#     causes_df = causes_df.rename(columns={"Reason": "Alert Type"})
#     st.dataframe(
#         causes_df[["Timestamp", "Appliance", "Alert Type", "Severity", "kWh"]].head(10),
#         use_container_width=True, hide_index=True,
#     )
# else:
#     wastage_rows = df[df["wastage_flag"]].copy().head(10)
#     if "Unix Timestamp" in df.columns:
#         wastage_rows["Timestamp"] = pd.to_datetime(
#             wastage_rows["Unix Timestamp"], unit="s"
#         ).dt.strftime("%Y-%m-%d  %H:%M")
#     else:
#         wastage_rows["Timestamp"] = pd.to_datetime(
#             1577836800 + wastage_rows.index * 1800, unit="s"
#         ).dt.strftime("%Y-%m-%d  %H:%M")
#     wastage_rows["Severity"] = np.where(
#         wastage_rows["spike_alert"] | wastage_rows["offpeak_alert"], "High", "Medium"
#     )
#     wastage_rows["Alert Type"] = np.where(
#         wastage_rows["spike_alert"], "Consumption Spike",
#         np.where(wastage_rows["offpeak_alert"], "Off-Peak Anomaly", "Prolonged Usage")
#     )
#     wastage_rows["kWh"] = wastage_rows["energy"].round(3)
#     st.dataframe(
#         wastage_rows[["Timestamp", "Alert Type", "Severity", "kWh"]],
#         use_container_width=True, hide_index=True,
#     )
# 
# # ── Footer ─────────────────────────────────────────────────────────────────────
# st.markdown("""
# <div class="footer">
#   Smart Energy Usage Predictor &nbsp;·&nbsp; Group B11 &nbsp;·&nbsp; Section 5.8 &nbsp;·&nbsp; Dashboard
# </div>
# """, unsafe_allow_html=True)

from pyngrok import ngrok
ngrok.kill()

!pkill ngrok
!pkill -f streamlit

from pyngrok import ngrok
import subprocess, threading, time

# Kill any previous tunnels
ngrok.kill()

def _run():
    subprocess.run([
        "streamlit", "run", "dashboard.py",
        "--server.port=8501", "--server.headless=true"
    ])

threading.Thread(target=_run, daemon=True).start()

time.sleep(5)

ngrok.set_auth_token("3CXceXnBeMU6zsQB1yHGjQ054Al_5F6GQc67zcksmnb6mUcX8")

public_url = ngrok.connect(8501, bind_tls=True)
print(public_url)

